# Support for GUI via Polkit    
- lineinfile:
    path: /etc/sssd/sssd.conf
    insertafter: '^access_provider = ad'
    line: 'ad_gpo_map_interactive = +polkit-1'
    
# Support for GUI via Polkit
- replace:
    path: /etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf
    
# Add Primary Group of User [usually Domain Users]    
    regexp: '^AdminIdentities=unix-group:sudo;unix-group:admin'
    replace: 'AdminIdentities=unix-group:sudo;unix-group:admin;unix-group:1860001131'
    
- service:
    name: sssd.service
    state: restarted
